# Generated by Django 3.2.5 on 2022-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=120)),
                ('semail', models.EmailField(max_length=254)),
                ('sdiv', models.IntegerField()),
                ('sdoj', models.DateField()),
                ('smarks', models.IntegerField()),
                ('smob', models.IntegerField()),
                ('sloc', models.CharField(max_length=120)),
            ],
        ),
    ]
