# Generated by Django 3.2.5 on 2022-07-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='sdiv',
            new_name='div',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sdoj',
            new_name='doj',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='semail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sloc',
            new_name='loc',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='smarks',
            new_name='marks',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='smob',
            new_name='mob',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sname',
            new_name='name',
        ),
    ]
